### ISSUE TITLE
As a traveller I want to post my vacation trips, so I can view all my vacation trips.

### ISSUE THREAD

**Issue by JManders07** [TravelXPToday/Portfolio#1]

**Comment by Artnooijen** [comment]
- [ ] Both students understand and reviewed the created subject.
- [ ] If necessary the subject is shown to the teacher, else both students aggreed it as done
- [ ] The feedback of the teacher or collaborator student is implemented (Or not if disagree).
- [ ] Has to be documented and integrated into both students Portfolio.
